source 'git@gitlab.alibaba-inc.com:alipods/specs.git'
source 'git@gitlab.alibaba-inc.com:alipods/specs-mirror.git'

ali_source 'alibaba-specs'
ali_source 'alibaba-specs-mirror'

platform :ios, '8.0'
#inhibit_all_warnings!

def common
    #pod 'WeexSDK', :path=>'../../'
    pod 'WeexSDK',  '0.13.0'
    pod 'WXDevtool', '~> 0.9.5'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
    
    # WeexGcanvas is added by Weex Plugin, more info at https://market.dotwe.org/ext/list.htm
    pod 'WeexGcanvas'
end

target 'WeexDemo' do
    common
end

target 'WeexUITestDemo' do
    common
end
